language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo add-apt-repository --yes ppa:zoogie/sdl2-snapshots
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake libsdl2-dev libsdl2-image-dev g++-4.8
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
script: cmake . -DRUN_GUI_TESTS=OFF && make && make test
